#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          8
#inner 9
#outer 11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Border
#Color 6b1223bb
bspc config active_border_color "#0a0047"
bspc config focused_border_color "#ff4499"
bspc config normal_border_color "#0a0047"

#focus
bspc config focus_follows_pointer true

picom -b &
